name: futurist
favicon: null
layout_spectrum: 0.5487382784485817
typography_spectrum: 0.6068015685304999
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.08353897952474654
  lightness: 0.7539237921591848
  saturation: 0.12337276083417237
  rhythmicContrast: 0.22225049720145762
purpose: []
